-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key medias.fk_medias_uploaded_by_id
ALTER TABLE medias ADD CONSTRAINT fk_medias_uploaded_by_id FOREIGN KEY (uploaded_by_id) REFERENCES users (id);
