-- Code generated by erm.
-- Schema migration.

-- step 1: create_table post_categories
CREATE TABLE post_categories (
    category_id uuid NOT NULL,
    post_id uuid NOT NULL,
    PRIMARY KEY (category_id, post_id)
);
