-- Code generated by erm.
-- Schema migration.

-- step 1: create_table user_roles
CREATE TABLE user_roles (
    role_id uuid NOT NULL,
    user_id uuid NOT NULL,
    PRIMARY KEY (role_id, user_id)
);
