-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key user_roles.fk_user_roles_user_id
ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id);
