-- Code generated by erm.
-- Schema migration.

-- step 1: create_table comments
CREATE TABLE comments (
    id uuid NOT NULL,
    post_id uuid NOT NULL,
    author_id uuid,
    parent_id uuid,
    author_name text,
    author_email text,
    author_url text,
    content text NOT NULL,
    status text NOT NULL DEFAULT 'pending' CONSTRAINT comments_status_enum_check CHECK (status IN ('pending', 'approved', 'spam', 'trash')),
    submitted_at timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);
