-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key post_categories.fk_post_categories_category_id
ALTER TABLE post_categories ADD CONSTRAINT fk_post_categories_category_id FOREIGN KEY (category_id) REFERENCES categories (id);
