-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key post_categories.fk_post_categories_post_id
ALTER TABLE post_categories ADD CONSTRAINT fk_post_categories_post_id FOREIGN KEY (post_id) REFERENCES posts (id);
