-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key comments.fk_comments_author_id
ALTER TABLE comments ADD CONSTRAINT fk_comments_author_id FOREIGN KEY (author_id) REFERENCES users (id);
