-- Code generated by erm.
-- Schema migration.

-- step 1: create_table medias
CREATE TABLE medias (
    id uuid NOT NULL,
    uploaded_by_id uuid,
    file_name text NOT NULL,
    mime_type text NOT NULL,
    storage_key text NOT NULL,
    url text NOT NULL,
    title text,
    alt_text text,
    caption text,
    description text,
    file_size_bytes integer,
    metadata jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);
