-- Code generated by erm.
-- Schema migration.

-- step 1: create_table roles
CREATE TABLE roles (
    id uuid NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    description text,
    capabilities jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);
