-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key categories.fk_categories_parent_id
ALTER TABLE categories ADD CONSTRAINT fk_categories_parent_id FOREIGN KEY (parent_id) REFERENCES categories (id);
