-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key post_tags.fk_post_tags_post_id
ALTER TABLE post_tags ADD CONSTRAINT fk_post_tags_post_id FOREIGN KEY (post_id) REFERENCES posts (id);
