-- Code generated by erm.
-- Schema migration.

-- step 1: create_table users
CREATE TABLE users (
    id uuid NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    display_name text,
    bio text,
    avatar_url text,
    website_url text,
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);
