-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key posts.fk_posts_featured_media_id
ALTER TABLE posts ADD CONSTRAINT fk_posts_featured_media_id FOREIGN KEY (featured_media_id) REFERENCES medias (id);
