-- Code generated by erm.
-- Schema migration.

-- step 1: create_table posts
CREATE TABLE posts (
    id uuid NOT NULL,
    author_id uuid NOT NULL,
    featured_media_id uuid,
    title text NOT NULL,
    slug text NOT NULL,
    status text NOT NULL DEFAULT 'draft' CONSTRAINT posts_status_enum_check CHECK (status IN ('draft', 'pending', 'private', 'published', 'archived')),
    type text NOT NULL DEFAULT 'post' CONSTRAINT posts_type_enum_check CHECK (type IN ('post', 'page', 'custom')),
    excerpt text,
    content text,
    seo jsonb,
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);
