-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key comments.fk_comments_parent_id
ALTER TABLE comments ADD CONSTRAINT fk_comments_parent_id FOREIGN KEY (parent_id) REFERENCES comments (id);
