-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key comments.fk_comments_post_id
ALTER TABLE comments ADD CONSTRAINT fk_comments_post_id FOREIGN KEY (post_id) REFERENCES posts (id);
