-- Code generated by erm.
-- Schema migration.

-- step 1: create_table categories
CREATE TABLE categories (
    id uuid NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    description text,
    parent_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);
