-- Code generated by erm.
-- Schema migration.

-- step 1: create_table options
CREATE TABLE options (
    id uuid NOT NULL,
    name text NOT NULL,
    value jsonb NOT NULL,
    autoload boolean NOT NULL DEFAULT FALSE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);
