-- Code generated by erm.
-- Schema migration.

-- step 1: add_foreign_key post_tags.fk_post_tags_tag_id
ALTER TABLE post_tags ADD CONSTRAINT fk_post_tags_tag_id FOREIGN KEY (tag_id) REFERENCES tags (id);
