package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"

	graphql1 "github.com/deicod/ermblog/graphql"
)

// ManagementStats is the resolver for the managementStats field.
func (r *queryResolver) ManagementStats(ctx context.Context) (*graphql1.ManagementStats, error) {
	posts, err := countThrough(ctx, r.postCounter())
	if err != nil {
		return nil, err
	}

	comments, err := countThrough(ctx, r.commentCounter())
	if err != nil {
		return nil, err
	}

	mediaItems, err := countThrough(ctx, r.mediaCounter())
	if err != nil {
		return nil, err
	}

	categories, err := countThrough(ctx, r.categoryCounter())
	if err != nil {
		return nil, err
	}

	tags, err := countThrough(ctx, r.tagCounter())
	if err != nil {
		return nil, err
	}

	users, err := countThrough(ctx, r.userCounter())
	if err != nil {
		return nil, err
	}

	stats := &graphql1.ManagementStats{
		Posts:      posts,
		Comments:   comments,
		MediaItems: mediaItems,
		Taxonomies: categories + tags,
		Users:      users,
	}

	return stats, nil
}
