package resolvers

// newEntityHooks configures optional GraphQL entity hooks.
//
// Modify this file to customize resolver behaviour. Populate the returned
// entityHooks with callbacks to run before mutating or returning ORM records.
// Leaving all fields unset preserves the default behaviour generated by erm.
func newEntityHooks() entityHooks {
        return entityHooks{}
}
