// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type Node interface {
	IsNode()
	GetID() string
}

type Category struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description,omitempty"`
	Color       *string   `json:"color,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

func (Category) IsNode()            {}
func (this Category) GetID() string { return this.ID }

type CategoryConnection struct {
	Edges      []*CategoryEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type CategoryEdge struct {
	Cursor string    `json:"cursor"`
	Node   *Category `json:"node,omitempty"`
}

type Comment struct {
	ID        string    `json:"id"`
	PostID    string    `json:"postId"`
	AuthorID  string    `json:"authorId"`
	ParentID  *string   `json:"parentId,omitempty"`
	Body      string    `json:"body"`
	IsEdited  bool      `json:"isEdited"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

func (Comment) IsNode()            {}
func (this Comment) GetID() string { return this.ID }

type CommentConnection struct {
	Edges      []*CommentEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node,omitempty"`
}

type CreateCategoryInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               *string    `json:"id,omitempty"`
	Name             *string    `json:"name,omitempty"`
	Slug             *string    `json:"slug,omitempty"`
	Description      *string    `json:"description,omitempty"`
	Color            *string    `json:"color,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type CreateCategoryPayload struct {
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
	Category         *Category `json:"category,omitempty"`
}

type CreateCommentInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               *string    `json:"id,omitempty"`
	PostID           *string    `json:"postId,omitempty"`
	AuthorID         *string    `json:"authorId,omitempty"`
	ParentID         *string    `json:"parentId,omitempty"`
	Body             *string    `json:"body,omitempty"`
	IsEdited         *bool      `json:"isEdited,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type CreateCommentPayload struct {
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
	Comment          *Comment `json:"comment,omitempty"`
}

type CreatePostInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               *string    `json:"id,omitempty"`
	AuthorID         *string    `json:"authorId,omitempty"`
	CategoryID       *string    `json:"categoryId,omitempty"`
	Title            *string    `json:"title,omitempty"`
	Slug             *string    `json:"slug,omitempty"`
	Excerpt          *string    `json:"excerpt,omitempty"`
	Body             *string    `json:"body,omitempty"`
	PublishedAt      *time.Time `json:"publishedAt,omitempty"`
	IsPublished      *bool      `json:"isPublished,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type CreatePostPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Post             *Post   `json:"post,omitempty"`
}

type CreatePostTagInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               *string    `json:"id,omitempty"`
	PostID           *string    `json:"postId,omitempty"`
	TagID            *string    `json:"tagId,omitempty"`
	AssignedAt       *time.Time `json:"assignedAt,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type CreatePostTagPayload struct {
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
	PostTag          *PostTag `json:"postTag,omitempty"`
}

type CreateTagInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               *string    `json:"id,omitempty"`
	Name             *string    `json:"name,omitempty"`
	Slug             *string    `json:"slug,omitempty"`
	Description      *string    `json:"description,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type CreateTagPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Tag              *Tag    `json:"tag,omitempty"`
}

type CreateUserInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               *string    `json:"id,omitempty"`
	Username         *string    `json:"username,omitempty"`
	Email            *string    `json:"email,omitempty"`
	Name             *string    `json:"name,omitempty"`
	Bio              *string    `json:"bio,omitempty"`
	AvatarURL        *string    `json:"avatarUrl,omitempty"`
	DisplayName      *string    `json:"displayName,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type CreateUserPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	User             *User   `json:"user,omitempty"`
}

type DeleteCategoryInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	ID               string  `json:"id"`
}

type DeleteCategoryPayload struct {
	ClientMutationID  *string `json:"clientMutationId,omitempty"`
	DeletedCategoryID string  `json:"deletedCategoryID"`
}

type DeleteCommentInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	ID               string  `json:"id"`
}

type DeleteCommentPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	DeletedCommentID string  `json:"deletedCommentID"`
}

type DeletePostInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	ID               string  `json:"id"`
}

type DeletePostPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	DeletedPostID    string  `json:"deletedPostID"`
}

type DeletePostTagInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	ID               string  `json:"id"`
}

type DeletePostTagPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	DeletedPostTagID string  `json:"deletedPostTagID"`
}

type DeleteTagInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	ID               string  `json:"id"`
}

type DeleteTagPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	DeletedTagID     string  `json:"deletedTagID"`
}

type DeleteUserInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	ID               string  `json:"id"`
}

type DeleteUserPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	DeletedUserID    string  `json:"deletedUserID"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID          string     `json:"id"`
	AuthorID    string     `json:"authorId"`
	CategoryID  *string    `json:"categoryId,omitempty"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Excerpt     *string    `json:"excerpt,omitempty"`
	Body        *string    `json:"body,omitempty"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
	IsPublished bool       `json:"isPublished"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

func (Post) IsNode()            {}
func (this Post) GetID() string { return this.ID }

type PostConnection struct {
	Edges      []*PostEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type PostEdge struct {
	Cursor string `json:"cursor"`
	Node   *Post  `json:"node,omitempty"`
}

type PostTag struct {
	ID         string    `json:"id"`
	PostID     string    `json:"postId"`
	TagID      string    `json:"tagId"`
	AssignedAt time.Time `json:"assignedAt"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

func (PostTag) IsNode()            {}
func (this PostTag) GetID() string { return this.ID }

type PostTagConnection struct {
	Edges      []*PostTagEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type PostTagEdge struct {
	Cursor string   `json:"cursor"`
	Node   *PostTag `json:"node,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type Tag struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

func (Tag) IsNode()            {}
func (this Tag) GetID() string { return this.ID }

type TagConnection struct {
	Edges      []*TagEdge `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type TagEdge struct {
	Cursor string `json:"cursor"`
	Node   *Tag   `json:"node,omitempty"`
}

type UpdateCategoryInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               string     `json:"id"`
	Name             *string    `json:"name,omitempty"`
	Slug             *string    `json:"slug,omitempty"`
	Description      *string    `json:"description,omitempty"`
	Color            *string    `json:"color,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type UpdateCategoryPayload struct {
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
	Category         *Category `json:"category,omitempty"`
}

type UpdateCommentInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               string     `json:"id"`
	PostID           *string    `json:"postId,omitempty"`
	AuthorID         *string    `json:"authorId,omitempty"`
	ParentID         *string    `json:"parentId,omitempty"`
	Body             *string    `json:"body,omitempty"`
	IsEdited         *bool      `json:"isEdited,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type UpdateCommentPayload struct {
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
	Comment          *Comment `json:"comment,omitempty"`
}

type UpdatePostInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               string     `json:"id"`
	AuthorID         *string    `json:"authorId,omitempty"`
	CategoryID       *string    `json:"categoryId,omitempty"`
	Title            *string    `json:"title,omitempty"`
	Slug             *string    `json:"slug,omitempty"`
	Excerpt          *string    `json:"excerpt,omitempty"`
	Body             *string    `json:"body,omitempty"`
	PublishedAt      *time.Time `json:"publishedAt,omitempty"`
	IsPublished      *bool      `json:"isPublished,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type UpdatePostPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Post             *Post   `json:"post,omitempty"`
}

type UpdatePostTagInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               string     `json:"id"`
	PostID           *string    `json:"postId,omitempty"`
	TagID            *string    `json:"tagId,omitempty"`
	AssignedAt       *time.Time `json:"assignedAt,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type UpdatePostTagPayload struct {
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
	PostTag          *PostTag `json:"postTag,omitempty"`
}

type UpdateTagInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               string     `json:"id"`
	Name             *string    `json:"name,omitempty"`
	Slug             *string    `json:"slug,omitempty"`
	Description      *string    `json:"description,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type UpdateTagPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Tag              *Tag    `json:"tag,omitempty"`
}

type UpdateUserInput struct {
	ClientMutationID *string    `json:"clientMutationId,omitempty"`
	ID               string     `json:"id"`
	Username         *string    `json:"username,omitempty"`
	Email            *string    `json:"email,omitempty"`
	Name             *string    `json:"name,omitempty"`
	Bio              *string    `json:"bio,omitempty"`
	AvatarURL        *string    `json:"avatarUrl,omitempty"`
	DisplayName      *string    `json:"displayName,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type UpdateUserPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	User             *User   `json:"user,omitempty"`
}

type User struct {
	ID          string    `json:"id"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	Name        *string   `json:"name,omitempty"`
	Bio         *string   `json:"bio,omitempty"`
	AvatarURL   *string   `json:"avatarUrl,omitempty"`
	DisplayName string    `json:"displayName"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }

type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type UserEdge struct {
	Cursor string `json:"cursor"`
	Node   *User  `json:"node,omitempty"`
}
